<h2> ======================================================</h2>
 <h1>MA477 - Theory and Applications of Data Science</h1> 
  <h1>Lesson 2: Introduction to NumPy</h1> 
 
 <h4>Dr. Valmir Bucaj</h4>
 <br>
 United States Military Academy, West Point, AY20-2
<h2>=======================================================</h2>

In [2]:
import numpy as np

<h2>==================================================</h2>
<br>
<h1>HOMEWORK #1</h1>

<h2>=================================================</h2>

<h3> Complete the following exercises. Document your code as necessary.</h3>
<br>

<ol>
<li><font size=3> Create a 5 by 7 numpy array of random integers with values between 3 and 11 inclusive. Then do the following:
    <ol> <li>Check the data type of the array</li>
        <li>Find the maximum of the entire array</li>
        <li>Find the minimum value of each row</li>
        <li>Find the index where the minimum value of each row occurs</li>
    </ol></font></li>
</ol>

In [4]:
#Your code for part A of Exercise 1 goes here
my_array = np.random.randint(3,12, size = (5,7))
my_array

my_array.dtype

dtype('int32')

In [5]:
#Your code for part B of Exercise 1 goes here
my_array.max()

11

In [6]:
#Your code for part C of Exercise 1 goes here
my_array.min(axis=1)

array([3, 3, 5, 7, 3])

In [7]:
#Your code for part D of Exercise 1 goes here
my_array.argmin(axis=1)

array([1, 5, 4, 0, 3], dtype=int64)

<ol start='2'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array: </font></li>

```python
#Result
array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])
```    
</ol>

In [8]:
#Your code for Exercise 2 goes here
np.arange(4,100,5)

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])

<ol start='3'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array: </font></li>

```python
#Result
array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])
```    
</ol>

In [9]:
#Your code for Exercise 3 goes here
np.arange(4,100,5).reshape (4,5) #https://realpython.com/how-to-use-numpy-arange/

array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])

<ol start='4'>
   
<li> <font size='3'>Create a 4 by 2 by 3 array of normally distributed values</font></li>
   
</ol>

In [10]:
#Your code for Exercise 4 goes here
np.random.randn(4,2,3)

array([[[ 0.26711315,  0.42861955,  1.02544879],
        [ 0.61340357,  0.54615532, -0.62662745]],

       [[ 0.01436733, -0.68166938, -0.26660968],
        [ 0.67603017,  0.42253958, -1.01086112]],

       [[-0.03940632, -1.2476695 , -1.24154693],
        [-0.36619694,  1.16373439,  0.73025204]],

       [[-0.59334434, -0.95071854,  0.69110343],
        [-0.44614146,  0.52666981,  1.42942443]]])

<ol start='5'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array(including the correct
    data type): </font></li>

```python
#Result
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]]
```    

</ol>

In [11]:
#Your code for Exercise 5 goes here
np.eye(6,6, k = -2,dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])

<ol start='6'>
   
<li> <font size='3'>Given the numpy array below </font></li>

```python
array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])
```    
<ol>
    <li>Enter the code below that selects only the last four elements:</li>

```python
#Result
array([27, 29, 31, 33])
```
<li>Enter the code that selects the following subarray:

```python
#Result
array([ 3,  9, 15, 21, 27, 33])
```
</ol>
</ol>

In [12]:
#Your code for part A of Exercise 6 goes here
my_array2 = np.arange(3,34,2)
my_array2[-4:]

array([27, 29, 31, 33])

In [13]:
#Your code for part B of Exercise 6 goes here
my_array2[my_array2%3==0]

array([ 3,  9, 15, 21, 27, 33])

<ol start='7'>
   
<li> <font size='3'>Given the 2D numpy array below </font></li>

```python
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])
```    
<ol>
    <li> Enter the code below that selects the element 72 on the last row</li>
    <br>
   <li>Enter the code below that selects the following subarray:</li>

```python
#Result
array([[76,  3],
       [26, 71],
       [38, 54]])
```
<li>Enter the code that selects the following subarray:

```python
#Result
array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])
```
</ol>
</ol>

In [14]:
#Your code for part A of Exercise 7 goes here
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])
arr_2d[4,-2]

72

In [15]:
#Your code for part B of Exercise 7 goes here
arr_2d[2:,3:5]

array([[76,  3],
       [26, 71],
       [38, 54]])

In [16]:
#Your code for part C of Exercise 7 goes here
arr_2d[1:4,:]

array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])

<ol start='8'>
   
<li> <font size='3'>Given the numpy array below </font></li>

```python
arr=np.arange(1,50,3)
array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])
```    
<ol>
    <li>Enter the code that selects all elements larger than 7 and smaller than 43:

```python
#Result
array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

```
   <li>Enter the code below that selects all even integers larger than 11 and smaller than 45:</li>

```python
#Result
array([16, 22, 28, 34, 40])
```
</ol>
</ol>

In [17]:
#Your code for part A of Exercise 8 goes here
arr=np.arange(1,50,3)
arr[(arr>7) & (arr<43)]

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

In [18]:
#Your code for part B of Exercise 8 goes here
arr[(arr%2==0) & (arr>11) & (arr<45)]

array([16, 22, 28, 34, 40])

<ol start='9'>
   
<li> <font size='3'>Create a 1D uniformly distributed array with 20 elements and compute: </font></li>


<ol>
    <li> Mean</li>

   <li>Standard Deviation</li>
   
   <li>Median</li>
   
   <li>Mean of its log values</li>
</ol>
</ol>

In [19]:
#Your code for part A of Exercise 9 goes here
new_array = np.random.rand(20)
new_array.mean()

0.45006545913497853

In [20]:
#Your code for part B of Exercise 9 goes here
new_array.std()

0.26877825992559995

In [21]:
#Your code for part C of Exercise 9 goes here
np.median(new_array)  #https://docs.scipy.org/doc/numpy/reference/generated/numpy.median.html.

0.427923843132869

In [22]:
#Your code for part D of Exercise 9 goes here
np.log10(new_array).mean()

-0.47036400685816887

<ol start='10'>
   
<li> <font size='3'>Write a function that:</font></li>
    <ol>
    <br>
   <li> takes a 1D Numpy array as input and prints out the <b>reversed</b> array with element type float</li>

For example, if you input the following array into your function
```python
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])
```
your function should print out

```python
array([23., 21., 19., 17., 15., 13., 11.,  9.,  7.,  5.,  3.,  1.])
```

<li> takes a 2D Numpy array as input and prints out a copy of the input array <b> flattened</b> to one dimension</li>

For example if the input array is:
```python
array([[7, 4, 8, 3],
       [6, 3, 4, 3],
       [4, 7, 5, 4]])
```
the output of your function should be
```python
array([7, 4, 8, 3, 6, 3, 4, 3, 4, 7, 5, 4])
```
</ol>
</ol>

In [23]:
#Your code for part A of Exercise 10 goes here
def reverse(arr):
    new_array = np.zeros(len(arr))
    j = -1
    for i in arr:
        new_array[j] = i
        j -=1
    return new_array

final_array = np.arange(1,24,2)

reverse(final_array)

array([23., 21., 19., 17., 15., 13., 11.,  9.,  7.,  5.,  3.,  1.])

In [24]:
#Your code for part B of Exercise 10 goes here
def flatten(arr):
    my_list = []
    for row in arr:
        for item in row:
            my_list += [item]
    return np.array(my_list)

final_array2 = np.random.randint(3,9,size=(3,4))

flatten(final_array2)

array([8, 6, 7, 5, 5, 3, 4, 8, 8, 7, 7, 5])

In [ ]:
## Works Cited

#"Numyp.median," SciPy.org, n.d. Accessed, Jan. 15, 2020. https://docs.scipy.org/doc/numpy/reference/
#generated/numpy.median.html.

#Stojiljkovic, Mirko. "NumPy arange(): How to Use np.arange()," Real Python, July 22, 2019. Accessed Jan. 15, 2020. 
#https://realpython.com/how-to-use-numpy-arange/.

